---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]
  - name: debian-7.11
    run_list:
      - recipe[apt]
  - name: debian-8.5
    run_list:
      - recipe[apt]
  - name: centos-6.7
    run_list:
      - recipe[yum]
      - recipe[yum-epel]
  - name: centos-7.2
    run_list:
      - recipe[yum]
      - recipe[yum-epel]

suites:
  - name: default
    run_list:
      - recipe[pyload::default]
    attributes:
  - name: debian-packages
    run_list:
      - recipe[pyload::packages]
    includes: [
      'ubuntu-12.04',
      'ubuntu-14.04',
      'ubuntu-16.04',
      'debian-7.11',
      'debian-8.5'
    ]
  - name: debian-specific-packages
    run_list:
      - recipe[pyload::packages]
    includes: [
      'ubuntu-14.04',
      'ubuntu-16.04',
      'debian-8.5'
    ]
  - name: rhel-packages
    run_list:
      - recipe[pyload::packages]
    includes: [
      'centos-6.7',
      'centos-7.2'
    ]
  - name: rhel-specific-packages-6
    run_list:
      - recipe[pyload::packages]
    includes: [
      'centos-6.7'
    ]
  - name: rhel-specific-packages-7
    run_list:
      - recipe[pyload::packages]
    includes: [
      'centos-7.2'
    ]
  - name: service-init
    run_list:
      - recipe[pyload::default]
    includes: [
      'ubuntu-12.04',
      'ubuntu-14.04',
      'debian-7.11',
      'centos-6.7'
    ]
  - name: service-systemd
    run_list:
      - recipe[pyload::default]
    includes: [
      'ubuntu-16.04',
      'debian-8.5',
      'centos-7.2'
    ]
