---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: doc

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: debian-7.10
  - name: debian-8.4
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[pyload::default]
    attributes:
  - name: debian-packages
    run_list:
      - recipe[apt]
      - recipe[pyload::packages]
    includes: [
      'ubuntu-12.04',
      'ubuntu-14.04',
      'ubuntu-16.04',
      'debian-7.10',
      'debian-8.4'
    ]
  - name: rhel-packages
    run_list:
      - recipe[yum]
      - recipe[yum-epel]
      - recipe[yum-repoforge]
      - recipe[pyload::packages]
    includes: [
      'centos-5.11',
      'centos-6.7',
      'centos-7.2'
    ]
  - name: service-init
    run_list:
      - recipe[pyload::default]
    includes: [
      'debian-7.10',
      'centos-5.11',
      'centos-6.7'
    ]
  - name: service-systemd
    run_list:
      - recipe[pyload::default]
    includes: [
      'ubuntu-16.04',
      'debian-8.4',
      'centos-7.2'
    ]
