---
driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec
  format: doc

platforms:
  - name: ubuntu-12.04
    driver:
      image: ubuntu:12.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update

  - name: ubuntu-14.04
    driver:
      image: ubuntu:14.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update

  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update

  - name: debian-7
    driver:
      image: debian:7
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install lsb-release -y

  - name: debian-8
    driver:
      image: debian:8
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install lsb-release -y

  - name: centos-6
    driver:
      image: centos:6
      platform: rhel
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN yum -y install which initscripts
    run_list:
      - recipe[yum]
      - recipe[yum-epel]

  - name: centos-7
    driver:
      image: centos:7
      platform: rhel
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install lsof which systemd-sysv initscripts
    run_list:
      - recipe[yum]
      - recipe[yum-epel]

  - name: fedora-22
    driver:
      image: fedora:22
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN dnf -y install yum which systemd-sysv initscripts

  - name: fedora-23
    driver:
      image: fedora:23
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN dnf -y install yum which systemd-sysv initscripts

  - name: fedora-24
    driver:
      image: fedora:24
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN dnf -y install yum which systemd-sysv initscripts

  # Cannot start a pyload due to python error
  #- name: opensuse-13.2
  #  driver:
  #    image: opensuse:13.2
  #    pid_one_command: /bin/systemd
  #    intermediate_instructions:
  #      - RUN zypper --non-interactive install aaa_base perl-Getopt-Long-Descriptive which
  #
  #- name: opensuse-42.1
  #  driver:
  #    image: opensuse:42.1
  #    pid_one_command: /bin/systemd
  #    intermediate_instructions:
  #      - RUN zypper --non-interactive install aaa_base perl-Getopt-Long-Descriptive which

suites:
  - name: default
    run_list:
      - recipe[pyload::default]
    attributes:
      pyload:
        accounts:
          test:
            user: test
            password: test
  - name: debian-packages
    run_list:
      - recipe[pyload::packages]
    attributes:
    includes: [
      'ubuntu-12.04',
      'ubuntu-14.04',
      'ubuntu-16.04',
      'debian-7',
      'debian-8'
    ]
  - name: fedora-packages
    run_list:
      - recipe[pyload::packages]
    attributes:
    includes: [
      'fedora-22',
      'fedora-23',
      'fedora-24'
    ]
  - name: rhel-packages
    run_list:
      - recipe[pyload::packages]
    attributes:
    includes: [
      'centos-6',
      'centos-7'
    ]
  - name: suse-packages
    run_list:
      - recipe[pyload::packages]
    attributes:
    includes: [
      'opensuse-13.2'
    ]
  - name: service-init
    run_list:
      - recipe[pyload::default]
    attributes:
    includes: [
      'ubuntu-12.04',
      'ubuntu-14.04',
      'debian-7',
      'centos-6'
    ]
  - name: service-systemd
    run_list:
      - recipe[pyload::default]
    attributes:
    includes: [
      'ubuntu-16.04',
      'debian-8',
      'centos-7',
      'fedora-22',
      'fedora-23',
      'fedora-24'
    ]
