---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: doc

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]
  - name: debian-7.11
    run_list:
      - recipe[apt]
  - name: debian-8.5
    run_list:
      - recipe[apt]
  - name: centos-6.8
    run_list:
      - recipe[yum]
      - recipe[yum-epel]
  - name: centos-7.2
    run_list:
      - recipe[yum]
      - recipe[yum-epel]
  - name: fedora-22
    run_list:
      - recipe[yum::dnf_yum_compat]
  - name: fedora-23
    run_list:
      - recipe[yum::dnf_yum_compat]
  - name: fedora-24
    run_list:
      - recipe[yum::dnf_yum_compat]

suites:
  - name: default
    run_list:
      - recipe[pyload::default]
    attributes:
  - name: debian-packages
    run_list:
      - recipe[pyload::packages]
    attributes:
    includes: [
      'ubuntu-12.04',
      'ubuntu-14.04',
      'ubuntu-16.04',
      'debian-7.11',
      'debian-8.5'
    ]
  - name: fedora-packages
    run_list:
      - recipe[pyload::packages]
    attributes:
    includes: [
      'fedora-22',
      'fedora-23',
      'fedora-24'
    ]
  - name: rhel-packages
    run_list:
      - recipe[pyload::packages]
    attributes:
    includes: [
      'centos-6.8',
      'centos-7.2'
    ]
  - name: service-init
    run_list:
      - recipe[pyload::default]
    attributes:
    includes: [
      'ubuntu-12.04',
      'ubuntu-14.04',
      'debian-7.11',
      'centos-6.8'
    ]
  - name: service-systemd
    run_list:
      - recipe[pyload::default]
    attributes:
    includes: [
      'ubuntu-16.04',
      'debian-8.5',
      'centos-7.2',
      'fedora-22',
      'fedora-23',
      'fedora-24'
    ]
