sudo: required
dist: trusty
language: ruby

# We will install the release of chefdk. Use chef-current-precise to install the pre-release.
addons:
  apt:
    sources:
      - chef-stable-precise
    packages:
      - chefdk

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=default-ubuntu-1204
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=default-debian-7
  - INSTANCE=default-debian-8
  - INSTANCE=default-centos-6
  - INSTANCE=default-centos-7
  - INSTANCE=default-fedora-22
  - INSTANCE=default-fedora-23
  - INSTANCE=default-fedora-24
  - INSTANCE=default-fedora-25
  - INSTANCE=default-opensuse-132
  - INSTANCE=debian-packages-ubuntu-1204
  - INSTANCE=debian-packages-ubuntu-1404
  - INSTANCE=debian-packages-ubuntu-1604
  - INSTANCE=debian-packages-debian-7
  - INSTANCE=debian-packages-debian-8
  - INSTANCE=fedora-packages-fedora-22
  - INSTANCE=fedora-packages-fedora-23
  - INSTANCE=fedora-packages-fedora-24
  - INSTANCE=fedora-packages-fedora-25
  - INSTANCE=rhel-packages-centos-6
  - INSTANCE=rhel-packages-centos-7
  - INSTANCE=suse-packages-opensuse-132
  - INSTANCE=service-init-ubuntu-1204
  - INSTANCE=service-init-ubuntu-1404
  - INSTANCE=service-init-debian-7
  - INSTANCE=service-init-centos-6
  - INSTANCE=service-systemd-ubuntu-1604
  - INSTANCE=service-systemd-debian-8
  - INSTANCE=service-systemd-centos-7
  - INSTANCE=service-systemd-fedora-22
  - INSTANCE=service-systemd-fedora-23
  - INSTANCE=service-systemd-fedora-24
  - INSTANCE=service-systemd-fedora-25
  - INSTANCE=service-systemd-opensuse-132
  - INSTANCE=service-upstart-ubuntu-1204
  - INSTANCE=service-upstart-ubuntu-1404

# Don't `bundle install`
install: echo "skip bundle install"

# Ensure we make ChefDK's Ruby the default
before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef gem install kitchen-dokken

script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/foodcritic . --exclude spec -f any -P
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/cookstyle
  - KITCHEN_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
